PracticaWeb/PracticaWeb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers

from flylo import views

router = routers.DefaultRouter()
router.register(r'flights', views.FlightViewSet)
router.register(r'aircrafts', views.AircraftViewSet)
router.register(r'categories', views.CategoryViewSet)
router.register(r'airlines', views.AirlineViewSet)
router.register(r'users', views.UserList)


urlpatterns = [
    url(r'^flylo/', include('flylo.urls', namespace='flylo')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

PracticaWeb/flylo/urls.py
# coding=utf-8
from django.conf.urls import url

from . import views

'''
Es defineixen els enllaços URL del website. Cal tenir encompte que com que es treballa amb diferents
llenguatges i es volen mostrar per URL cal considerar dues URL per cada cas (amb llenguatge i sense).
En cas d'executar una URL sense llenguatge, el sistema serà prou intel·ligent per detectar l'idioma
favorit de l'usuari i adjuntar el llenguatge a la URL.
'''

urlpatterns = [

    url(r'^(?P<language>[a-z]{2})/$', views.index, name='index'),
    url(r'^$', views.index, name='index'),

    url(r'^(?P<language>[a-z]{2})/shopping-cart/$', views.shopping_cart, name='shopping-cart'),
    url(r'^(?P<language>[a-z]{2})/buy/success/$', views.buy_success, name='buy-success'),
    url(r'^buy/success/$', views.buy_success, name='buy-success'),
    url(r'^(?P<language>[a-z]{2})/buy/$', views.buy, name='buy'),
    url(r'^buy/$', views.buy, name='buy'),

    url(r'^(?P<language>[a-z]{2})/buying/$', views.buying, name='buying'),
    url(r'^buying/$', views.buying, name='buying'),

    url(r'^(?P<language>[a-z]{2})/flights/$', views.flights, name='flights'),
    url(r'^flights/$', views.flights, name='flights'),

    url(r'^(?P<language>[a-z]{2})/flights/(?P<departure>.*)/$', views.flights, name='flights'),
    url(r'^flights/(?P<departure>.*)/$', views.flights, name='flights'),

    url(r'^(?P<language>[a-z]{2})/flight/(?P<flight_number>.*)/airline/(?P<name>.*)/info/$', views.airline_info, name='airline-info'),
    url(r'^flight/(?P<flight_number>.*)/airline/(?P<name>.*)/info/$', views.airline_info, name='airline-info'),

    url(r'^(?P<language>[a-z]{2})/flight/(?P<flight_number>.*)/info/$', views.flight_info, name='flight-info'),
    url(r'^flight/(?P<flight_number>.*)/info/$', views.flight_info, name='flight-info'),

    url(r'^(?P<language>[a-z]{2})/aircraft/(?P<name>.*)/info/$', views.aircraft_info, name='aircraft-info'),
    url(r'^aircraft/(?P<name>.*)/info/$', views.aircraft_info, name='aircraft-info'),

    url(r'^(?P<language>[a-z]{2})/flight/(?P<flight_number>.*)/checkin/success/$', views.do_checkin, name='checkin-success'),
    url(r'^flight/(?P<flight_number>.*)/checkin/success/$', views.do_checkin, name='checkin-success'),

    url(r'^(?P<language>[a-z]{2})/flight/(?P<flight_number>.*)/checkin/(?P<seats>.*)/$', views.checkin, name='checkin'),
    url(r'^flight/(?P<flight_number>.*)/checkin/(?P<seats>.*)/$', views.checkin, name='checkin'),

    url(r'^(?P<language>[a-z]{2})/users/login/$', views.login, name='login'),
    url(r'^users/login$', views.login, name='login'),

    url(r'^(?P<language>[a-z]{2})/users/register/$', views.register, name='register'),
    url(r'^users/register', views.register, name='register'),

    url(r'^(?P<language>[a-z]{2})/users/me/$', views.userhome, name='userhome'),
    url(r'^users/me', views.userhome, name='userhome'),

    url(r'^(?P<language>[a-z]{2})/users/logout/$', views.logout, name='logout'),
    url(r'^users/logout', views.logout, name='logout'),

    url(r'^(?P<language>[a-z]{2})/errors/transaction/$', views.transaction_error, name='transaction-error'),
    url(r'^errors/transaction', views.transaction_error, name='transaction-error'),

    url(r'^(?P<language>[a-z]{2})/comparator/$', views.comparator, name='comparator'),
    url(r'^comparator/$', views.comparator, name='comparator'),

    url(r'^remove-flight/(?P<flight_id>.*)/$', views.remove_flight_from_cart, name='remove-flight-from-cart'),
    url(r'^get-free/(?P<flight_number>.*)/$', views.get_free, name='get-free'),
]

PracticaWeb/flylo/views.py
# coding=utf-8
import os
from sqlite3 import IntegrityError

from django.contrib import auth
from django.contrib.auth.models import User
from django.db import transaction
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from rest_framework import viewsets

from flylo import permissions
from flylo.models import Flight, Aircraft, Airline, ShoppingCart, ClientFlights, Client, Category
from flylo.settings import Settings
from .serializers import FlightSerializer, AircraftSerializer, CategorySerializer, AirlineSerializer, UserSerializer


#########################################
########### Vistes de la WEB ############
#########################################


@require_http_methods(["GET", "POST"])
def login(request, language=''):
    """ Gestiona la pàgina de login al sistema """

    # es redirigeix a l'usuari al seu userhome si ja està logat
    if request.user.is_authenticated():
        return redirect("/flylo/" + language + "/users/me")

    # informació bàsica de la pàgina actual
    page_info = Settings.get_page_info(request, language)

    # s'afegeix l'idioma si la URL no el porta
    if language == '':
        cookie_language = request.COOKIES.get('language') if request.COOKIES.get('language') else Settings.DEFAULT_SITE_LANGUAGE
        return redirect(Settings.redirect_to(page_info, cookie_language))

    context = {
        'request': request
    }

    # es mira si s'arriba per POST, si és així vol dir que s'ha omplert el formulari
    # d'inici de sessió
    if request.method == 'POST' and request.POST['in-login'] == '1':

        # es reben els camps d'autentificació
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')

        # s'autentifica l'usuari
        user = auth.authenticate(username=username, password=password)

        # es comprova que els camps de text hagin estat omplerts adientment
        if username.strip() and password.strip():

            # es mira que l'usuari estigui actiu al sistema
            if user is not None and user.is_active:

                # es loga l'usuari al sistema i es redirigeix a la seva pàgina privada
                auth.login(request, user)

                # es comprova si el motiu del login és un intent de compra i si és així enlloc de redirigir
                # a l'userhome fem que l'usuari torni a la pantalla del carret de compra disposat a executar
                # la compra dels vols
                if 'redirect_because_user_not_logged_in' in request.session.keys():

                    # es neteja la variable de sessió de redirecció i es redirigeix allà on toca
                    request.session['redirect_because_user_not_logged_in'] = ''
                    return HttpResponseRedirect("/flylo/" + language + "/buy")

                return HttpResponseRedirect("/flylo/" + language + "/users/me")

            else:
                context['error_message'] = page_info['LANG_USER_NOT_EXISTS']

        else:
            context['error_message'] = page_info['LANG_ALL_FILEDS_ARE_REQUIRED']

    # s'afegeix la infomació de la pàgina al context
    context.update(page_info)

    # es genera la resposta del servidor amb la sol·licitud la pàgina destí i el context
    response = render(request, 'flylo/login.html', context)

    # es crea la cookie de l'idioma si cal
    Settings.set_cookie_language(response, language)

    return response


@require_http_methods(["GET", "POST"])
def register(request, language=''):
    """ Registra un usuari en el sistema """

    # es redirigeix a l'usuari al seu userhome si ja està logat
    if request.user.is_authenticated():
        return redirect("/flylo/" + language + "/users/me")

    # informació bàsica de la pàgina actual
    page_info = Settings.get_page_info(request, language)

    # s'afegeix l'idioma si la URL no el porta
    if language == '':
        cookie_language = request.COOKIES.get('language') if request.COOKIES.get('language') else Settings.DEFAULT_SITE_LANGUAGE
        return redirect(Settings.redirect_to(page_info, cookie_language))

    context = {
        'request': request
    }

    # es mira si s'arriba per POST, si és així vol dir que s'ha omplert el formulari
    # de registre
    if request.method == 'POST' and request.POST['in-register'] == '1':

        # es reben els camps d'autentificació
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        email = request.POST.get('email', '')

        # es comprova que tots els camps tinguin valor
        if username.strip() and password.strip() and email.strip():

            # no es permetrà repetir nom d'usuari
            try:
                User.objects.get(username=username)
                context['error_message'] = page_info['LANG_USER_EXISTS']

            # si l'usuari no existeix es procedeix al seu registre, es loga i finalment es redirigeix
            # a la seva pàgina privada d'usuari.
            except User.DoesNotExist:

                # es crea l'usuari
                user = User.objects.create_user(username, email, password)
                user.save()

                # se li afegeix rol de client i s'inicia el client amb mil euros
                client = Client(user=user, money=1000.0)
                client.save()

                # s'autologueja al registrar-se
                auth.login(request, user)

                # es comprova si el motiu del registre és un intent de compra i si és així enlloc de redirigir
                # a l'userhome fem que l'usuari torni a la pantalla del carret de compra disposat a executar
                # la compra dels vols
                if 'redirect_because_user_not_logged_in' in request.session.keys():

                    # es neteja la variable de sessió de redirecció i es redirigeix allà on toca
                    request.session['redirect_because_user_not_logged_in'] = ''
                    return HttpResponseRedirect("/flylo/" + language + "/buy")

                return HttpResponseRedirect("/flylo/" + language + "/users/me")

        else:
            context['error_message'] = page_info['LANG_ALL_FILEDS_ARE_REQUIRED']

    # s'afegeix la infomació de la pàgina al context
    context.update(page_info)

    # es genera la resposta del servidor amb la sol·licitud la pàgina destí i el context
    response = render(request, 'flylo/register.html', context)

    # es crea la cookie de l'idioma si cal
    Settings.set_cookie_language(response, language)

    return response


@require_http_methods("GET")
def logout(request, language=''):
    """ Tanca la sessió d'usuari i redirecciona a login """

    auth.logout(request)
    return HttpResponseRedirect("/flylo/" + language + "/users/login")


@require_http_methods(["GET", "POST"])
def userhome(request, language=''):
    """
    Representa la vista de la pàgina privada d'usuari
    Des d'aquesta vista serà possible realitzar els CheckIn dels vols adquirits
    """

    # per accedir a aquesta és condició impresicindible estar autenticat
    if not request.user.is_authenticated():
        return HttpResponseRedirect("/flylo/" + language + "/users/login")

    # informació bàsica de la pàgina actual
    page_info = Settings.get_page_info(request, language)

    # s'afegeix l'idioma si la URL no el porta
    if language == '':
        cookie_language = request.COOKIES.get('language') if request.COOKIES.get('language') else Settings.DEFAULT_SITE_LANGUAGE
        return redirect(Settings.redirect_to(page_info, cookie_language))

    client_flights_items = ClientFlights.objects.filter(username=request.user.username)
    client_flights = []

    # s'obtenen els atributs que falten de la relació 'Flight' original.
    for flight in client_flights_items:
        flight_obj = Flight.objects.get(flight_number=flight.flight_number)
        flight_obj.airline = flight.airline
        flight_obj.seats = flight.seats
        flight_obj.category = flight.category
        flight_obj.status = flight.status
        flight_obj.passengers_names = flight.passengers_names.split('/')
        client_flights.append(flight_obj)

        # s'adapta el preu en funció de l'algorisme de càlcul de preu de vol
        flight_obj.price = Flight.compute_flight_price_algorithm(flight_obj)

    context = {
        'request': request,
        'client_flights': client_flights
    }

    # s'intenta accedir al client i es gestiona si es tracta de l'admin
    # normalment l'admin ppodria actuar com a client. Això és, però, una mesura de seguretat.
    try:
        user = User.objects.get(username=request.user.username)
        client = Client.objects.get(user=user)
        context['client'] = client

    except Client.DoesNotExist:
        context['error_client'] = True

    # s'afegeix la infomació de la pàgina al context
    context.update(page_info)

    # es genera la resposta del servidor amb la sol·licitud la pàgina destí i el context
    response = render(request, 'flylo/userhome.html', context)

    # es crea la cookie de l'idioma si cal
    Settings.set_cookie_language(response, language)

    return response


@require_http_methods("GET")
def index(request, language=''):
    """ Gestiona el template 'index.html' """

    # informació bàsica de la pàgina
    page_info = Settings.get_page_info(request, language)

    # s'assigna l'idioma de la pàgina (cookie/default)
    language, redirection = Settings.add_language_from_cookie(request, language)

    # es mira si cal redireccionar per afegir l'idioma de la cookie i es fa si escau
    if redirection:
        return redirect(page_info['current_path'] + language)

    # s'intenta fer la consulta requerida per paràmetre
    try:
        query = Flight.objects.values("location_departure").distinct()

    # si la consulta falla es redirecciona a 404

PracticaWeb/flylo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- es carrega el directori static que conté algunes utilitats del web (estils, imatges, etc) -->
    {% load static %}

    <meta charset="UTF-8">
    <title>{{ meta.title }}</title>

    <!-- Meta-informació de la pàgina actual -->
    <meta name="title" content="{{ meta.title }}" />
    <meta name="description" content="{{ meta.description }}" />
    <meta name="keywords" content="{{ meta.keywords }}" />
    <meta name="author" content="{{ meta.author }}">

    <!-- estils css -->
    <link rel="stylesheet" type="text/css" href="{% static 'flylo/css/style.css' %}" />
    <link rel="stylesheet" href="http://fontawesome.io/assets/font-awesome/css/font-awesome.css" />

    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'flylo/images/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'flylo/images/favicon.ico' %}" type="image/x-icon">

    <!-- funcions js -->
    <script src="{% static 'flylo/js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'flylo/js/functions.js' %}"></script>

</head>

<body>

    <!-- es carrega el fitxer utils que conté les funcions -->
    {% load flylo_util %}

    <!-- PopUp per mostrar qualsevol contingut, per defecte comença amagat -->
    <div id="overlay-container" class="absolute display">
        <div class="wrapper">
            <div class="container margin-top-40 radius-5 shadow padding-20">
            </div>
        </div>
    </div>

    <!-- Cada pàgina porta un ID <current_page> que es correspon amb el nom del seu arxiu html -->
    <div id="{{ current_page }}" class="wrapper">

        <label id="language" class="pull-right padding-10">
            <span>{{ LANG_LANGUAGE }}:&nbsp;</span>
            <select onchange="change_lang(this.value, '{{ current_language }}', '{{ current_path }}')">
                <option {% if current_language == 'ca' %} selected {% endif %} value="ca">Català</option>
                <option {% if current_language == 'en' %} selected {% endif %} value="en">English</option>
            </select>
        </label>

        <header class="shadow radius-5 margin-top-10">
            <p class="logo">
                <a href="{% url 'flylo:index' current_language %}"><i class="fa fa-send"></i> Fly<span>Lo</span></a>
            </p>

            <ul>
                <a href="{% url 'flylo:buy' current_language %}" class="pull-right">
                    <li class="option-menu pull-right"><i class="fa fa-shopping-cart"></i>&nbsp;&nbsp{{ LANG_SHOPPING_CART }} <small><strong>({% get_length request.session.shopping_cart.cart %})</strong></small></li>
                </a>

                {% if user.is_authenticated %}

                    <a href="{% url 'flylo:logout' current_language %}" class="pull-right">
                        <li class="option-menu pull-right"><i class="fa fa-sign-out"></i>&nbsp;&nbsp{{ LANG_LOGOUT }}</li>
                    </a>

                    <a href="{% url 'flylo:userhome' current_language %}" class="pull-right">
                        <li class="option-menu pull-right"><i class="fa fa-home"></i>&nbsp;&nbsp{{ user.username }}</li>
                    </a>

                {% else %}
                    <a href="{% url 'flylo:login' current_language %}" class="pull-right">
                        <li class="option-menu pull-right"><i class="fa fa-sign-in"></i>&nbsp;&nbsp{{ LANG_LOGIN }}</li>
                    </a>
                {% endif %}

                <a href="{% url 'flylo:flights' %}" class="pull-right">
                    <li class="option-menu pull-right"><i class="fa fa-rocket"></i>&nbsp;&nbsp{{ LANG_FLIGHTS }}</li>
                </a>

                <a href="{% url 'flylo:comparator' current_language %}" class="pull-right">
                    <li class="option-menu pull-right"><i class="fa fa-bar-chart"></i>&nbsp;&nbsp{{ LANG_COMPARATOR }}</li>
                </a>

            </ul>
        </header>

        <!-- Aquest contingut serà diferent segons la pàgina actual -->
        {% block content %}
        {% endblock %}

        <footer class="shadow radius-5">
            <p class="logo"><a href="{% url 'flylo:index' current_language %}">Fly<span>Lo</span></a></p>
            <p class="slogan">{{ LANG_SLOGAN }}</p>
            <p class="info margin-top-40">{{ LANG_SUBJECT }}: <strong>{{ LANG_SUBJECT_NAME }}</strong></p>
            <p class="info margin-bottom-20">{{ LANG_AUTHORS }}: <strong>{{ LANG_AUTHORS_NAME }}</strong></p>
        </footer>
    </div>

</body>
</html>