PracticaWeb/PracticaWeb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers

from flylo import views

router = routers.DefaultRouter()
router.register(r'flights', views.FlightViewSet)
router.register(r'aircrafts', views.AircraftViewSet)
router.register(r'categories', views.CategoryViewSet)
router.register(r'airlines', views.AirlineViewSet)
router.register(r'users', views.UserList)


urlpatterns = [
    url(r'^flylo/', include('flylo.urls', namespace='flylo')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

PracticaWeb/flylo/urls.py
# coding=utf-8
from django.conf.urls import url

from . import views

'''
Es defineixen els enllaços URL del website. Cal tenir encompte que com que es treballa amb diferents
llenguatges i es volen mostrar per URL cal considerar dues URL per cada cas (amb llenguatge i sense).
En cas d'executar una URL sense llenguatge, el sistema serà prou intel·ligent per detectar l'idioma
favorit de l'usuari i adjuntar el llenguatge a la URL.
'''

urlpatterns = [

    url(r'^(?P<language>[a-z]{2})/$', views.index, name='index'),
    url(r'^$', views.index, name='index'),

    url(r'^(?P<language>[a-z]{2})/shopping-cart/$', views.shopping_cart, name='shopping-cart'),
    url(r'^(?P<language>[a-z]{2})/buy/success/$', views.buy_success, name='buy-success'),
    url(r'^buy/success/$', views.buy_success, name='buy-success'),
    url(r'^(?P<language>[a-z]{2})/buy/$', views.buy, name='buy'),
    url(r'^buy/$', views.buy, name='buy'),

    url(r'^(?P<language>[a-z]{2})/buying/$', views.buying, name='buying'),
    url(r'^buying/$', views.buying, name='buying'),

    url(r'^(?P<language>[a-z]{2})/flights/$', views.flights, name='flights'),
    url(r'^flights/$', views.flights, name='flights'),

    url(r'^(?P<language>[a-z]{2})/flights/(?P<departure>.*)/$', views.flights, name='flights'),
    url(r'^flights/(?P<departure>.*)/$', views.flights, name='flights'),

    url(r'^(?P<language>[a-z]{2})/flight/(?P<flight_number>.*)/airline/(?P<name>.*)/info/$', views.airline_info, name='airline-info'),
    url(r'^flight/(?P<flight_number>.*)/airline/(?P<name>.*)/info/$', views.airline_info, name='airline-info'),

    url(r'^(?P<language>[a-z]{2})/flight/(?P<flight_number>.*)/info/$', views.flight_info, name='flight-info'),
    url(r'^flight/(?P<flight_number>.*)/info/$', views.flight_info, name='flight-info'),

    url(r'^(?P<language>[a-z]{2})/aircraft/(?P<name>.*)/info/$', views.aircraft_info, name='aircraft-info'),
    url(r'^aircraft/(?P<name>.*)/info/$', views.aircraft_info, name='aircraft-info'),

    url(r'^(?P<language>[a-z]{2})/flight/(?P<flight_number>.*)/checkin/success/$', views.do_checkin, name='checkin-success'),
    url(r'^flight/(?P<flight_number>.*)/checkin/success/$', views.do_checkin, name='checkin-success'),

    url(r'^(?P<language>[a-z]{2})/flight/(?P<flight_number>.*)/checkin/(?P<seats>.*)/$', views.checkin, name='checkin'),
    url(r'^flight/(?P<flight_number>.*)/checkin/(?P<seats>.*)/$', views.checkin, name='checkin'),

    url(r'^(?P<language>[a-z]{2})/users/login/$', views.login, name='login'),
    url(r'^users/login$', views.login, name='login'),

    url(r'^(?P<language>[a-z]{2})/users/register/$', views.register, name='register'),
    url(r'^users/register', views.register, name='register'),

    url(r'^(?P<language>[a-z]{2})/users/me/$', views.userhome, name='userhome'),
    url(r'^users/me', views.userhome, name='userhome'),

    url(r'^(?P<language>[a-z]{2})/users/logout/$', views.logout, name='logout'),
    url(r'^users/logout', views.logout, name='logout'),

    url(r'^(?P<language>[a-z]{2})/errors/transaction/$', views.transaction_error, name='transaction-error'),
    url(r'^errors/transaction', views.transaction_error, name='transaction-error'),

    url(r'^(?P<language>[a-z]{2})/comparator/$', views.comparator, name='comparator'),
    url(r'^comparator/$', views.comparator, name='comparator'),

    url(r'^remove-flight/(?P<flight_id>.*)/$', views.remove_flight_from_cart, name='remove-flight-from-cart'),
    url(r'^get-free/(?P<flight_number>.*)/$', views.get_free, name='get-free'),
]

PracticaWeb/flylo/views.py
# coding=utf-8
import os
from sqlite3 import IntegrityError

from django.contrib import auth
from django.contrib.auth.models import User
from django.db import transaction
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from rest_framework import viewsets

from flylo import permissions
from flylo.models import Flight, Aircraft, Airline, ShoppingCart, ClientFlights, Client, Category
from flylo.settings import Settings
from .serializers import FlightSerializer, AircraftSerializer, CategorySerializer, AirlineSerializer, UserSerializer


#########################################
########### Vistes de la WEB ############
#########################################


@require_http_methods(["GET", "POST"])
def login(request, language=''):
    """ Gestiona la pàgina de login al sistema """

    # es redirigeix a l'usuari al seu userhome si ja està logat
    if request.user.is_authenticated():
        return redirect("/flylo/" + language + "/users/me")

    # informació bàsica de la pàgina actual
    page_info = Settings.get_page_info(request, language)

    # s'afegeix l'idioma si la URL no el porta
    if language == '':
        cookie_language = request.COOKIES.get('language') if request.COOKIES.get('language') else Settings.DEFAULT_SITE_LANGUAGE
        return redirect(Settings.redirect_to(page_info, cookie_language))

    context = {
        'request': request
    }

    # es mira si s'arriba per POST, si és així vol dir que s'ha omplert el formulari
    # d'inici de sessió
    if request.method == 'POST' and request.POST['in-login'] == '1':

        # es reben els camps d'autentificació
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')

        # s'autentifica l'usuari
        user = auth.authenticate(username=username, password=password)

        # es comprova que els camps de text hagin estat omplerts adientment
        if username.strip() and password.strip():

            # es mira que l'usuari estigui actiu al sistema
            if user is not None and user.is_active:

                # es loga l'usuari al sistema i es redirigeix a la seva pàgina privada
                auth.login(request, user)

                # es comprova si el motiu del login és un intent de compra i si és així enlloc de redirigir
                # a l'userhome fem que l'usuari torni a la pantalla del carret de compra disposat a executar
                # la compra dels vols
                if 'redirect_because_user_not_logged_in' in request.session.keys():

                    # es neteja la variable de sessió de redirecció i es redirigeix allà on toca
                    request.session['redirect_because_user_not_logged_in'] = ''
                    return HttpResponseRedirect("/flylo/" + language + "/buy")

                return HttpResponseRedirect("/flylo/" + language + "/users/me")

            else:
                context['error_message'] = page_info['LANG_USER_NOT_EXISTS']

        else:
            context['error_message'] = page_info['LANG_ALL_FILEDS_ARE_REQUIRED']

    # s'afegeix la infomació de la pàgina al context
    context.update(page_info)

    # es genera la resposta del servidor amb la sol·licitud la pàgina destí i el context
    response = render(request, 'flylo/login.html', context)

    # es crea la cookie de l'idioma si cal
    Settings.set_cookie_language(response, language)

    return response


@require_http_methods(["GET", "POST"])
def register(request, language=''):
    """ Registra un usuari en el sistema """

    # es redirigeix a l'usuari al seu userhome si ja està logat
    if request.user.is_authenticated():
        return redirect("/flylo/" + language + "/users/me")

    # informació bàsica de la pàgina actual
    page_info = Settings.get_page_info(request, language)

    # s'afegeix l'idioma si la URL no el porta
    if language == '':
        cookie_language = request.COOKIES.get('language') if request.COOKIES.get('language') else Settings.DEFAULT_SITE_LANGUAGE
        return redirect(Settings.redirect_to(page_info, cookie_language))

    context = {
        'request': request
    }

    # es mira si s'arriba per POST, si és així vol dir que s'ha omplert el formulari
    # de registre
    if request.method == 'POST' and request.POST['in-register'] == '1':

        # es reben els camps d'autentificació
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        email = request.POST.get('email', '')

        # es comprova que tots els camps tinguin valor
        if username.strip() and password.strip() and email.strip():

            # no es permetrà repetir nom d'usuari
            try:
                User.objects.get(username=username)
                context['error_message'] = page_info['LANG_USER_EXISTS']

            # si l'usuari no existeix es procedeix al seu registre, es loga i finalment es redirigeix
            # a la seva pàgina privada d'usuari.
            except User.DoesNotExist:

                # es crea l'usuari
                user = User.objects.create_user(username, email, password)
                user.save()

                # se li afegeix rol de client i s'inicia el client amb mil euros
                client = Client(user=user, money=1000.0)
                client.save()

                # s'autologueja al registrar-se
                auth.login(request, user)

                # es comprova si el motiu del registre és un intent de compra i si és així enlloc de redirigir
                # a l'userhome fem que l'usuari torni a la pantalla del carret de compra disposat a executar
                # la compra dels vols
                if 'redirect_because_user_not_logged_in' in request.session.keys():

                    # es neteja la variable de sessió de redirecció i es redirigeix allà on toca
                    request.session['redirect_because_user_not_logged_in'] = ''
                    return HttpResponseRedirect("/flylo/" + language + "/buy")

                return HttpResponseRedirect("/flylo/" + language + "/users/me")

        else:
            context['error_message'] = page_info['LANG_ALL_FILEDS_ARE_REQUIRED']

    # s'afegeix la infomació de la pàgina al context
    context.update(page_info)

    # es genera la resposta del servidor amb la sol·licitud la pàgina destí i el context
    response = render(request, 'flylo/register.html', context)

    # es crea la cookie de l'idioma si cal
    Settings.set_cookie_language(response, language)

    return response


@require_http_methods("GET")
def logout(request, language=''):
    """ Tanca la sessió d'usuari i redirecciona a login """

    auth.logout(request)
    return HttpResponseRedirect("/flylo/" + language + "/users/login")


@require_http_methods(["GET", "POST"])
def userhome(request, language=''):
    """
    Representa la vista de la pàgina privada d'usuari
    Des d'aquesta vista serà possible realitzar els CheckIn dels vols adquirits
    """

    # per accedir a aquesta és condició impresicindible estar autenticat
    if not request.user.is_authenticated():
        return HttpResponseRedirect("/flylo/" + language + "/users/login")

    # informació bàsica de la pàgina actual
    page_info = Settings.get_page_info(request, language)

    # s'afegeix l'idioma si la URL no el porta
    if language == '':
        cookie_language = request.COOKIES.get('language') if request.COOKIES.get('language') else Settings.DEFAULT_SITE_LANGUAGE
        return redirect(Settings.redirect_to(page_info, cookie_language))

    client_flights_items = ClientFlights.objects.filter(username=request.user.username)
    client_flights = []

    # s'obtenen els atributs que falten de la relació 'Flight' original.
    for flight in client_flights_items:
        flight_obj = Flight.objects.get(flight_number=flight.flight_number)
        flight_obj.airline = flight.airline
        flight_obj.seats = flight.seats
        flight_obj.category = flight.category
        flight_obj.status = flight.status
        flight_obj.passengers_names = flight.passengers_names.split('/')
        client_flights.append(flight_obj)

        # s'adapta el preu en funció de l'algorisme de càlcul de preu de vol
        flight_obj.price = Flight.compute_flight_price_algorithm(flight_obj)

    context = {
        'request': request,
        'client_flights': client_flights
    }

    # s'intenta accedir al client i es gestiona si es tracta de l'admin
    # normalment l'admin ppodria actuar com a client. Això és, però, una mesura de seguretat.
    try:
        user = User.objects.get(username=request.user.username)
        client = Client.objects.get(user=user)
        context['client'] = client

    except Client.DoesNotExist:
        context['error_client'] = True

    # s'afegeix la infomació de la pàgina al context
    context.update(page_info)

    # es genera la resposta del servidor amb la sol·licitud la pàgina destí i el context
    response = render(request, 'flylo/userhome.html', context)

    # es crea la cookie de l'idioma si cal
    Settings.set_cookie_language(response, language)

    return response


@require_http_methods("GET")
def index(request, language=''):
    """ Gestiona el template 'index.html' """

    # informació bàsica de la pàgina
    page_info = Settings.get_page_info(request, language)

    # s'assigna l'idioma de la pàgina (cookie/default)
    language, redirection = Settings.add_language_from_cookie(request, language)

    # es mira si cal redireccionar per afegir l'idioma de la cookie i es fa si escau
    if redirection:
        return redirect(page_info['current_path'] + language)

    # s'intenta fer la consulta requerida per paràmetre
    try:
        query = Flight.objects.values("location_departure").distinct()

    # si la consulta falla es redirecciona a 404

PracticaWeb/flylo/templates/flylo/checkin-success.html
{% extends "base.html" %}

<!--
base.html és l'arxiu que conté els contenidors base per a totes les vistes (header, footer, etc..)
Totes les pàgines del projecte han d'extendre de base.html
-->

{% load static %}
{% block content %}

<div class="container margin-top-40 padding-20 radius-5 shadow padding-bottom-50">

    <h2 class="margin-bottom-30">
        <i class="fa fa-check text-limegreen"></i> &nbsp;{{ LANG_FLIGHT_CHECKIN_SUCCESS }} {{ flight_number }} !
    </h2>

    <div class="dashed padding-20 margin-bottom-20">
        <p>{{ LANG_FLIGHT_CHECKIN_SUCCESS_TEXT }}</p>
    </div>

    <div class="clear margin-top-40"></div>
    <a href="{% url 'flylo:index' current_language %}" class="button large-button radius-5 shadow"><i class="fa fa-automobile"></i> {{ LANG_RETURN_TO_INDEX }}</a>
    <a href="{% url 'flylo:userhome' current_language %}" class="button large-button brown radius-5 shadow"><i class="fa fa-user"></i> {{ LANG_RETURN_TO_USERHOME }}</a>
</div>
{% endblock %}

PracticaWeb/flylo/templates/flylo/flight-info.html
{% extends "base.html" %}

<!--
base.html és l'arxiu que conté els contenidors base per a totes les vistes (header, footer, etc..)
Totes les pàgines del projecte han d'extendre de base.html
-->

{% load static %}
{% block content %}

<div class="container margin-top-40 padding-20 radius-5 shadow">

    <h2 class="margin-bottom-30"><i class="fa fa-info-circle"></i> &nbsp;{{ LANG_FLIGHT_DETAILS_FROM_ID }}<strong>{{ flight.flight_number }}</strong></h2>
    <div class="flight-details padding-20 overflow-hidden">

        <div class="pull-left">
            <p class="margin-bottom-10">{{ LANG_FLIGHT_ID }}: <strong>{{ flight.flight_number }}</strong></p>
            <p class="margin-bottom-10">{{ LANG_ESTIMATED_DEPARTURE_DATE }}: <strong>{{ flight.estimated_time_departure.date }}</strong></p>
            <p class="margin-bottom-10">{{ LANG_ESTIMATED_DEPARTURE_TIME }}: <strong>{{ flight.estimated_time_departure.time }}</strong></p>
            <p class="margin-bottom-10">{{ LANG_ESTIMATED_ARRIVAL_DATE }}: <strong>{{ flight.estimated_time_arrival.date }}</strong></p>
            <p class="margin-bottom-10">{{ LANG_ESTIMATED_ARRIVAL_TIME }}: <strong>{{ flight.estimated_time_arrival.time }}</strong></p>
            <p class="margin-bottom-10">{{ LANG_AIRPORT_DEPARTURE }}: <strong>{{ flight.location_departure }}</strong></p>
            <p class="margin-bottom-10">{{ LANG_AIRPORT_ARRIVAL }}: <strong>{{ flight.location_arrival }}</strong></p>
            <p class="margin-bottom-10">{{ LANG_DISTANCE_FLIGHT }}: <strong>{{ flight.distance }} <small>(Km)</small></strong></p>
            <p class="margin-bottom-10">{{ LANG_AIRPLANE }}: <strong>{{ flight.aircraft.name }}</strong></p>
            <p class="margin-bottom-10">{{ LANG_PRICE }}: <strong>{{ flight.price }}</strong></p>

        </div>
        <div class="page-image pull-right">
            <img class="img-resposive" src="{% static 'flylo/images/favicon.png' %}" alt="flight" width="200" />
        </div>
    </div>

    <div class="airlines padding-20">
        <div class="pull-left margin-left-20">
            <p class="margin-bottom-20">{{ LANG_AIRLINES_FLIGHT }}:</p>
            {% for airline in flight.airlines.all %}
                <a href="{% url 'flylo:airline-info' current_language flight.flight_number airline.name %}" class="button small-button radius-5 shadow pull-left {% if forloop.counter > 1  %}margin-left-10{% endif %}"><i class="fa fa-location-arrow"></i>&nbsp;&nbsp;{{ airline.long_name }}</a>
            {% endfor %}
        </div>

        <div class="pull-right margin-right-20">
            <p class="margin-bottom-20">{{ LANG_AIRCRAFT_FLIGHT }}: <strong>{{ flight.aircraft.name }}</strong></p>
            <a href="{% url 'flylo:aircraft-info' current_language flight.aircraft.name %}" class="button large-button shadow radius-5 pull-left">{{ LANG_AIRCRAFT_INFO }} <strong>{{ flight.aircraft.name }}</strong></a>
        </div>
    </div>

    <div class="margin-top-30">
        <a href="{% url 'flylo:flights' current_language flight.location_departure %}" class="button brown large-button shadow radius-5 pull-left"><i class="fa fa-angle-double-left"></i> {{ LANG_RETURN_TO_FLIGHT_LIST }}</a>

        <a class="button brown large-button shadow radius-5 pull-right" href="{% url 'flylo:comparator' current_language %}?flight_id={{ flight.flight_number }}&departure={{ flight.location_departure }}&arrival={{ flight.location_arrival }}&departure_time={{ flight.estimated_time_departure }}&arrival_time={{ flight.estimated_time_arrival }}">
            <i class="fa fa-bar-chart-o"></i>&nbsp;&nbsp;{{ LANG_USE_COMPARATOR_GOR_THIS_FLIGHT }}
        </a>

    </div>
</div>
{% endblock %}

PracticaWeb/flylo/templates/flylo/flights.html
{% extends "base.html" %}

<!--
base.html és l'arxiu que conté els contenidors base per a totes les vistes (header, footer, etc..)
Totes les pàgines del projecte han d'extendre de base.html
-->

<!-- es carrega el fitxer utils que conté les funcions -->
{% load flylo_util %}

{% block content %}

<div class="container margin-top-40 padding-20 radius-5 shadow">

    {% if departure != 'all' %}
        <h2 class="margin-bottom-30"><i class="fa fa-space-shuttle"></i> &nbsp;{{ LANG_AVAILABLE_FLIGHTS_FROM }}: <strong>{{ departure }}</strong></h2>
    {% else %}
        <h2 class="margin-bottom-30"><i class="fa fa-space-shuttle"></i> &nbsp;{{ LANG_AVAILABLE_ALL_FLIGHTS }}</h2>
    {% endif %}

    <!-- es crea el formulari per post per passar les dades per body -->
    <form action="{% url 'flylo:shopping-cart' current_language %}" method="post">
        {% csrf_token %}
        {% if flights %}

            <ul>
                <!-- itera tots els vols -->
                {% for flight in flights %}

                    <!-- només es mostren aquells vols que ténen seients disponibles -->
                    {% if flight.number_of_available_seats > 0 %}

                        <!--
                        s'obté el nombre de seients prèviament seleccionats (si existeixen) i l'aerolinia per fer matching
                        en cas que l'usuari torni a la pàgina de vols amb el carret de la compra plè
                        -->
                        {% if flight.id|stringformat:"i" in request.session.shopping_cart.cart.keys %}
                            {% get_num_seats_from_flight_id request.session flight.id as num_seats %}
                            {% get_airline_from_flight_id request.session flight.id as selected_airline %}
                            {% get_return_from_flight_id request.session flight.id as flight_return %}
                            {% get_category_from_flight_id request.session flight.id as selected_category %}
                            {% get_true as show_return %}
                        {% else %}
                            {% get_one as num_seats %}
                            {% get_false as show_return %}
                        {% endif %}

                        <!-- Cada item de la llista representa un vol -->
                        <li id="item-flight-list-{{ flight.id }}" class="padding-20 overflow-hidden relative">

                            <!--
                            S'iclouen els vols de retorn que per defecte estan amagats
                            -->
                            {% include 'flylo/includes/flight_returns.html' %}

                            <!--
                            S'iclouen les opcions de vol que apareixen quan es fa click al checkbox
                            Per defecte estan en 'hide'
                            -->
                            {% include 'flylo/includes/flight_options.html' %}

                            <!-- Descripció del vol -->
                            <p class="clear pull-left">{{ LANG_FLIGHT_ID }}: <span>{{ flight.flight_number}}</span></p>
                            <p id="user-seats-{{ flight.id }}" class="display pull-right"><span id="num-seats-{{ flight.id }}"></span></p>
                            <p class="clear">{{ LANG_AIRPORT_DEPARTURE }}: <span>{{ flight.location_departure }}</span></p>
                            <p class="clear">{{ LANG_AIRPORT_ARRIVAL }}: <span>{{ flight.location_arrival }}</span></p>
                            <p class="clear">{{ LANG_DEPARTURE_MOMENT }}: <span>{{ flight.estimated_time_departure }}</span></p>
                            <p class="clear">{{ LANG_ARRIVAL_MOMENT }}: <span>{{ flight.estimated_time_arrival }}</span></p>
                            <p class="clear">Price: <span>{{ flight.price }} &euro;</span></p>

                            {% if flight.flight_number in user_flights_ids %}

                                <!-- Botó per anar a fer el check-in si el vol ha estat prèviament adquirit -->
                                <a class="margin-top-20 pull-right button small-button shadow radius-5 bg-black" style="padding:7px 15px" href="{% url 'flylo:userhome' current_language %}">
                                    <i class="fa fa-star"></i>&nbsp;&nbsp;{{ LANG_DO_CHECKIN_OR_VIEW_STATUS }}
                                </a>
                                <p class="margin-top-30 text-orangered pull-left"><strong>{{ LANG_ACQUIRED }}</strong></p>

                            {% else %}

                                <!-- Botó per anar a la pàgina d'informació del vol -->
                                <a class="margin-top-20 pull-left button small-button shadow radius-5" href="{% url 'flylo:flight-info' current_language flight.flight_number %}">
                                    <i class="fa fa-info-circle"></i>&nbsp;&nbsp;{{ LANG_SEE_FLIGHT_INFO }}
                                </a>

                                <!-- Botó amb cjeckbox per afegir el vol al carret de la compra -->
                                <label id="label_flight_{{ flight.id }}" class="margin-top-20 pull-right button brown small-button radius-5 shadow">
                                    <input {% if flight.id|stringformat:"i" in request.session.shopping_cart.cart.keys %}checked {% endif %}
                                            type="checkbox" name="flight_{{ flight.id }}"
                                            id="flight_{{ flight.id }}" value="{{ flight.id }}" onclick="selectFlightOptions('{{ flight.id }}', '{{ LANG_SELECTED }}', '{{ LANG_ADD_TO_CART }}', '/flylo/remove-flight/{{ flight.id }}/');" />
                                            <span id="lang-add-to-cart-{{ flight.id }}">{{ LANG_ADD_TO_CART }}</span> &nbsp;<i class="fa fa-shopping-cart"></i>
                                </label>

                            {% endif %}

                            <div class="clear"></div>

                            <!-- Demana a l'usuari si vol un vol de tornada -->
                            <p id="return-flights-{{ flight.id }}" class="margin-top-10 font-size-15 pull-left" {% if not show_return %} style="visibility: hidden"{% endif %}>
                                <a class="return-button-flights shadow radius-5" href="javascript:" onclick="selectFlightsReturn('{{ flight.id }}')">{{ LANG_WANT_RETURN_FLIGHT_QUESTION }}</a>
                            </p>

                            <!-- botó per fer ús del comparador de vols -->
                            <p id="compare-{{ flight.id }}" class="margin-top-10 font-size-15 pull-right">
                                <a href="{% url 'flylo:comparator' current_language %}?flight_id={{ flight.flight_number }}&departure={{ flight.location_departure }}&arrival={{ flight.location_arrival }}&departure_time={{ flight.estimated_time_departure }}&arrival_time={{ flight.estimated_time_arrival }}">
                                    <i class="fa fa-bar-chart-o"></i>&nbsp;&nbsp;{{ LANG_EQUIPARATE_FLIGHT }}
                                </a>
                            </p>

                            <input type="hidden" name="airline_return_{{ flight.id }}" id="airline_return_{{ flight.id }}" value="{{ flight_return.airline }}" />
                        </li>
                        <!-- /Fi de vol -->

                    {%  endif %}
                {% endfor %}
            </ul>

        {% else %}
            <p>No Flights are available.</p>
        {% endif %}

        <div class="clear"></div>

        <div class="margin-top-40">
            <a href="{% url "flylo:index" current_language %}" class="button large-button shadow radius-5 pull-left"><i class="fa fa-angle-double-left"></i> {{ LANG_RETURN_TO_BACK }}</a>
        </div>

        <!-- Només si hi ha vols es permet reservar-los mitjançant el carret de la compar -->
        {% if flights %}
            <input type="submit" value="{{ LANG_SAVE_AND_GO_TO_SHOPPING_CART }}" class="submit-flights button large-button brown shadow radius-5 pull-right" />
        {% endif %}

    </form>
</div>

<script type="text/javascript">

    /**
     * Quan la pàgina estigui preparada...
     */
    $(document).ready(function(){
        showOptionsForSelectedFlights();
    });



    /**
     * Mostra el nombre de seients que han estat encarregats durant la sessió
     */
    var showOptionsForSelectedFlights = function() {

        // s'iteren els vols del carret de compra de la sessió
        {% for flight in request.session.shopping_cart.cart.items %}

            // es mostra l'icona de l'usuari que indica que aquell vol està al shopping cart
            $("#user-seats-{{ flight.0 }}").show();

            // s'obtenen, dela sessió, el nombre de seients i l'aeroilinia
            var selectedAirline = '{{ flight.1.airline }}';
            var numSeats = '{{ flight.1.seats }}';

            // es mostra el nombre de seients reservats si aquest està definit a la sessió
            $("#num-seats-{{ flight.0 }}").html(numSeats + ' <i class="fa fa-user"></i> <small>(' + selectedAirline + ')</small>');

            // es mostra el vol de retorn si aquest el tenia seleccionat a la sessió
            {% if flight.1.return %}

                var flightReturnText = '<span style="color:#F60"><u>Ret</u>: ';
                flightReturnText += '{{ flight.1.return.flight_number }}: ';
                flightReturnText += '{{ flight.1.return.location_departure }}-{{ flight.1.return.location_arrival }} ';
                flightReturnText += '({{ flight.1.return.airline }}) ';
                flightReturnText += '{{ flight.1.return.estimated_time_departure }}</span>';

                $("#return-flights-{{ flight.0 }}").css("visibility", "visible").html(flightReturnText);
                $("#compare-{{ flight.0 }}").hide();

            {% endif %}

            $("#lang-add-to-cart-{{ flight.0 }}").html('{{ LANG_ADDED }}');

        {% endfor %}
    };
</script>

{% endblock %}